@startuml package_diagram

skinparam linetype ortho
skinparam packageStyle rectangle
skinparam defaultTextAlignment center

left to right direction

folder "UI" {
    
    folder "UI Controller" {
        class AddNewExpenseController
        class AddNewTaskController
        class AddUserToGroupController
        class ExpenseController_UI
        class GroupChatController_UI
        class KollAppController
        class LoginController
        class RegisterController
        class RegisterGroupController
    }
    folder "Client" {
        class ExpenseApiHandler
        class GroupApiHandler
        class GroupChatApiHandler
        class ToDoListApiHandler
        class UserApiHandler
    }  
}

folder "Core" {
    class Expense
    class GroupChat
    class Message
    class Settlement
    class Task
    class ToDoList
    class User
    class UserGroup
}

folder "API" {
    folder "Controller" {
        class ExpenseController
        class GroupChatController
        class GroupController
        class ToDoListController
        class UserController
    }

    folder "Service" {
        class ExpenseService
        class GroupChatService
        class GroupService
        class ToDoListService
        class UserService
    }

    folder "Persistence" {
    }
}

"Client" -down-> "Controller" : HTTP Requests
"UI Controller" -down-> "Client" : Delegate Logic
"Controller" -down-> "Service" : Delegates Logic
"Service" -down-> "Persistence" : Mannage Data

"Service" -down-> "Core" : Uses Model
"Controller" -down-> "Core" : Uses Model


@enduml