image: maven:3.9.9-eclipse-temurin-17-alpine

stages:
  - build
  - test

maven-build:
  stage: build
  script:
    - echo "Building the project..."
    - cd kollapp
    - mvn clean install -DskipTests -DskipUITests
    - mvn compile

maven-test:
  stage: test
  script:
    - echo "Running tests..."
    - cd kollapp
    - mvn test -DskipUITests=true
